### ISSUE TITLE
No fixed units in scss variables

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/aurelia-slickgrid#420]
## I'm submitting a Feature request

Its super nice that the plugin provides all the scss files so that these can be properly included in the users styling while allowing to easily modify default flagged variables.

At several occasions though, the unit fixed by default making customization unnecessarily harder to accommodate to a system which say builds up on rem's instead of px's.

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Aurelia           |
| Aurelia-Slickgrid | 2.21.0
| TypeScript        |
| Operating System  |
| NPM/Node/Yarn     |

### Context

1. A minor example
 [$autocomplete-tpl2-container-list-width](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/styles/_variables.scss#L167) where the value is `#{$autocomplete-tpl2-width - 15px} !default;`
2. more severe issue
 [.slick-pagination - font-size](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/styles/slick-pagination.scss#L15) value: `$font-size-base - 1px`

### Possible Solution

Perhaps we could extract these corrections or optimizations of the calculation into a separate default variable so it can be adapted by the consumer as well.

**Comment by ghiscoding** [comment]
Hmm the thing is I never really understood this principle of `em`, `rem`, I know it's some kind of form of adapting your font to be viewed the same on both desktop/mobile but I never understood how to work and implement that kind of principle. If you find a way to fix this with a PR then please go ahead, else I'm not sure what to do here since I always work in `px` since that is mostly what I know and SlickGrid is all written in `px` as well. If that requires to review the entire set of `scss` file, that would be a huge task.

**Comment by zewa666** [comment]
In my quick sample I've had bootstrap used anyways. Now the default setup was/is that the it defines `$font-size-base:              1rem !default`. Rem's primary reason was for font-scaling and the ease of respecting the users preferences plus easier scaling for devs (1rem = 16px by most default browser settings). Here's a [more detailed explanation](https://stackoverflow.com/questions/11799236/should-i-use-px-or-rem-value-units-in-my-css#:~:text=I%20recommend%20using%20rem%20units,will%20scale%20up%20px%20units.). 

In general I wanted to understand why they were written in the restrictive way in the begin. Since it sounds your not opposed to extract vars and this was most likely just the result of quickly adding the feature, how about I collect the input from our designer and come back to you with a set of improvement suggestions than? This will take a while since we're just starting out with the plugin.

**Comment by zewa666** [comment]
As initially mentioned I'm not particularly interested personally in the individual use-cases, our designer for sure is, but more that by default adding the scss file to our subset together with ours which included bootstrap caused our scss-compile step to fail. One of the issues was the mentioned `.slick-pagination - font-size`. So my intention was to fix whats necessary so that one doesn't blindly runs into compile issues straight away, but I wanted to see at the same time whether you're opposed to introducing more variables or not, which seems like its fine for you.

**Comment by ghiscoding** [comment]
Yes I'm totally open for any improvements, adding variables is not a problem either. If you find a quick way to find this then I'm happy to get a PR

**Comment by ghiscoding** [comment]
@zewa666 I've pushed a commit with some fixes for all the missing `calc()` and also moved any pixel calculation with SASS variable outside of regular SASS files (mainly moved these calculation into the `_variables.scss`). It's not perfect, there's a lot of pixel use and calculation still but all the SASS ones are in the variable file so that should fix your issue I believe.

**Comment by zewa666** [comment]
I had the PR pretty much done but got sick yesterday so couldnt finish it. Hopefully i'll be back at work on Friday and take a look at your stuff and provide any leftovers if still exist. Thanks for the work @ghiscoding

**Comment by ghiscoding** [comment]
ah ok well take care then 😉 
I haven't released any new version though, but I guess you could try without and feel free to do any other PR if I missed anything. I'll create a new version when you feel it's time. Thanks

**Comment by zewa666** [comment]
Looks good for me. Looking forward to the next release.

**Comment by ghiscoding** [comment]
New version is out, there are few other changes and fixes as well, see [release 2.22.0](https://github.com/ghiscoding/aurelia-slickgrid/releases)
